---
abstract: 'use HTML::HTML5::Parser with HTML::Zoom'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  strictures: 1
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: HTML::Zoom::Parser::HH5P
name: HTML-Zoom-Parser-HH5P
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  HTML::HTML5::Entities: 0
  HTML::HTML5::Parser: 0.206
  HTML::Zoom: 0.009007
  Moo: 1.000000
  XML::LibXML: 2
  namespace::clean: 0
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=HTML-Zoom-Parser-HH5P
  homepage: https://metacpan.org/release/HTML-Zoom-Parser-HH5P
  license: http://dev.perl.org/licenses/
  repository: https://metacpan.org/release/HTML-Zoom-Parser-HH5P
version: 0.002
